// src/components/layout/TimelinePanel.svelte
<script lang="ts">
  import { LayoutDashboard } from "lucide-svelte";
</script>

<div class="w-full h-full flex items-center justify-center text-slate-400 dark:text-slate-600 bg-white dark:bg-slate-900 transition-colors duration-300">
  <div class="text-center">
    <LayoutDashboard class="w-16 h-16 mx-auto mb-4 opacity-10 dark:opacity-20" />
    <p>Timeline View (Coming Soon)</p>
  </div>
</div>

// src/components/layout/TimelinePanel.tsx
import { LayoutDashboard } from "lucide-react";

export default function TimelinePanel() {
  return (
    <div className="w-full h-full flex items-center justify-center text-slate-400 dark:text-slate-600 bg-white dark:bg-slate-900 transition-colors duration-300">
      <div className="text-center">
        <LayoutDashboard className="w-16 h-16 mx-auto mb-4 opacity-10 dark:opacity-20" />
        <p>Timeline View (Coming Soon)</p>
      </div>
    </div>
  );
}
